apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-31T14:22:25Z"
  name: carts-canary
  resourceVersion: "97016"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: dc4fbfd7-fbe9-11e9-a713-020e3bad5712
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
