apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - sockshop-dev-gateway.sockshop-dev
  - mesh
  hosts:
  - carts.sockshop-dev.jahn.demo.keptn.sh
  - carts
  - carts.sockshop-dev
  http:
  - route:
    - destination:
        host: carts.sockshop-dev.svc.cluster.local
